name: Docker Image CI

on:
  push:
    branches: [ "main" ]
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  REPO: ${{secrets.REPO}}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # first action : checkout source code
    - name: docker login
      run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN 
    - name: Build the Docker image # push The image to the docker hub
      run: docker build . --file Dockerfile --tag latest
    - name: Docker Push
      run: docker push lknutson/tools
    
